# Generated by Django 4.2 on 2023-05-02 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_at']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='startTime',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='endTime',
            new_name='due_at',
        ),
        migrations.RemoveField(
            model_name='status',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='task',
            name='goalTime',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.AddField(
            model_name='status',
            name='name',
            field=models.CharField(default='Incomplete', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='New Task', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default='Incomplete', on_delete=django.db.models.deletion.PROTECT, to='tasks.status'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Project', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.project'),
        ),
    ]
